language: java
jdk:
- oraclejdk8
sudo: false
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: springboot-devopos
  #on:
   # repo: vsalmei/springboot-devopos
after_success:
  - mvn clean test jacoco:report coveralls:report
